//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.10.102
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedContentModels
{
	/// <summary>CtaBox</summary>
	[PublishedContentModel("ctaBox")]
	public partial class CtaBox : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "ctaBox";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public CtaBox(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<CtaBox, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Box link
		///</summary>
		[ImplementPropertyType("boxLink")]
		public IPublishedContent BoxLink
		{
			get { return this.GetPropertyValue<IPublishedContent>("boxLink"); }
		}

		///<summary>
		/// Box picture
		///</summary>
		[ImplementPropertyType("boxPicture")]
		public IPublishedContent BoxPicture
		{
			get { return this.GetPropertyValue<IPublishedContent>("boxPicture"); }
		}

		///<summary>
		/// Box text
		///</summary>
		[ImplementPropertyType("boxText")]
		public string BoxText
		{
			get { return this.GetPropertyValue<string>("boxText"); }
		}

		///<summary>
		/// Headline
		///</summary>
		[ImplementPropertyType("headline")]
		public string Headline
		{
			get { return this.GetPropertyValue<string>("headline"); }
		}
	}
}
