//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.10.102
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedContentModels
{
	/// <summary>Frontpage</summary>
	[PublishedContentModel("frontpage")]
	public partial class Frontpage : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "frontpage";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Frontpage(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Frontpage, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Adresse
		///</summary>
		[ImplementPropertyType("adresse")]
		public string Adresse
		{
			get { return this.GetPropertyValue<string>("adresse"); }
		}

		///<summary>
		/// Cvr
		///</summary>
		[ImplementPropertyType("cvr")]
		public string Cvr
		{
			get { return this.GetPropertyValue<string>("cvr"); }
		}

		///<summary>
		/// Email
		///</summary>
		[ImplementPropertyType("email")]
		public string Email
		{
			get { return this.GetPropertyValue<string>("email"); }
		}

		///<summary>
		/// Facebook
		///</summary>
		[ImplementPropertyType("facebook")]
		public string Facebook
		{
			get { return this.GetPropertyValue<string>("facebook"); }
		}

		///<summary>
		/// Feature headline
		///</summary>
		[ImplementPropertyType("featureHeadline")]
		public string FeatureHeadline
		{
			get { return this.GetPropertyValue<string>("featureHeadline"); }
		}

		///<summary>
		/// Feature image
		///</summary>
		[ImplementPropertyType("featureImage")]
		public IPublishedContent FeatureImage
		{
			get { return this.GetPropertyValue<IPublishedContent>("featureImage"); }
		}

		///<summary>
		/// Feature link
		///</summary>
		[ImplementPropertyType("featureLink")]
		public IPublishedContent FeatureLink
		{
			get { return this.GetPropertyValue<IPublishedContent>("featureLink"); }
		}

		///<summary>
		/// Feature subtext
		///</summary>
		[ImplementPropertyType("featureSubtext")]
		public IHtmlString FeatureSubtext
		{
			get { return this.GetPropertyValue<IHtmlString>("featureSubtext"); }
		}

		///<summary>
		/// Google maps link
		///</summary>
		[ImplementPropertyType("googleMapsLink")]
		public string GoogleMapsLink
		{
			get { return this.GetPropertyValue<string>("googleMapsLink"); }
		}

		///<summary>
		/// Hero Caption
		///</summary>
		[ImplementPropertyType("heroCaption")]
		public string HeroCaption
		{
			get { return this.GetPropertyValue<string>("heroCaption"); }
		}

		///<summary>
		/// Hero Description
		///</summary>
		[ImplementPropertyType("heroDescription")]
		public IHtmlString HeroDescription
		{
			get { return this.GetPropertyValue<IHtmlString>("heroDescription"); }
		}

		///<summary>
		/// Hero Header
		///</summary>
		[ImplementPropertyType("heroHeader")]
		public string HeroHeader
		{
			get { return this.GetPropertyValue<string>("heroHeader"); }
		}

		///<summary>
		/// Hero Img
		///</summary>
		[ImplementPropertyType("heroImg")]
		public IPublishedContent HeroImg
		{
			get { return this.GetPropertyValue<IPublishedContent>("heroImg"); }
		}

		///<summary>
		/// Hero link
		///</summary>
		[ImplementPropertyType("heroLink")]
		public IPublishedContent HeroLink
		{
			get { return this.GetPropertyValue<IPublishedContent>("heroLink"); }
		}

		///<summary>
		/// Logo
		///</summary>
		[ImplementPropertyType("logo")]
		public IPublishedContent Logo
		{
			get { return this.GetPropertyValue<IPublishedContent>("logo"); }
		}

		///<summary>
		/// Projekt overskrift
		///</summary>
		[ImplementPropertyType("projectHeadline")]
		public string ProjectHeadline
		{
			get { return this.GetPropertyValue<string>("projectHeadline"); }
		}

		///<summary>
		/// Projekt link
		///</summary>
		[ImplementPropertyType("projectLink")]
		public IPublishedContent ProjectLink
		{
			get { return this.GetPropertyValue<IPublishedContent>("projectLink"); }
		}

		///<summary>
		/// Projekt subtekst
		///</summary>
		[ImplementPropertyType("projectSubtext")]
		public IHtmlString ProjectSubtext
		{
			get { return this.GetPropertyValue<IHtmlString>("projectSubtext"); }
		}

		///<summary>
		/// Projekt tal
		///</summary>
		[ImplementPropertyType("projektTal")]
		public IEnumerable<IPublishedContent> ProjektTal
		{
			get { return this.GetPropertyValue<IEnumerable<IPublishedContent>>("projektTal"); }
		}

		///<summary>
		/// Services
		///</summary>
		[ImplementPropertyType("services")]
		public IEnumerable<IPublishedContent> Services
		{
			get { return this.GetPropertyValue<IEnumerable<IPublishedContent>>("services"); }
		}

		///<summary>
		/// Services overskrift
		///</summary>
		[ImplementPropertyType("servicesHeadline")]
		public string ServicesHeadline
		{
			get { return this.GetPropertyValue<string>("servicesHeadline"); }
		}

		///<summary>
		/// Services subtekst
		///</summary>
		[ImplementPropertyType("servicesSubtext")]
		public string ServicesSubtext
		{
			get { return this.GetPropertyValue<string>("servicesSubtext"); }
		}

		///<summary>
		/// Telefon
		///</summary>
		[ImplementPropertyType("telefon")]
		public string Telefon
		{
			get { return this.GetPropertyValue<string>("telefon"); }
		}

		///<summary>
		/// Testimonial overskrift
		///</summary>
		[ImplementPropertyType("testimonialHeadline")]
		public string TestimonialHeadline
		{
			get { return this.GetPropertyValue<string>("testimonialHeadline"); }
		}

		///<summary>
		/// Testimonials
		///</summary>
		[ImplementPropertyType("testimonials")]
		public IEnumerable<IPublishedContent> Testimonials
		{
			get { return this.GetPropertyValue<IEnumerable<IPublishedContent>>("testimonials"); }
		}

		///<summary>
		/// Testimonials subtekst
		///</summary>
		[ImplementPropertyType("testimonialSubtext")]
		public string TestimonialSubtext
		{
			get { return this.GetPropertyValue<string>("testimonialSubtext"); }
		}

		///<summary>
		/// Twitter
		///</summary>
		[ImplementPropertyType("twitter")]
		public string Twitter
		{
			get { return this.GetPropertyValue<string>("twitter"); }
		}

		///<summary>
		/// Website Title
		///</summary>
		[ImplementPropertyType("websiteTitle")]
		public string WebsiteTitle
		{
			get { return this.GetPropertyValue<string>("websiteTitle"); }
		}

		///<summary>
		/// Youtube
		///</summary>
		[ImplementPropertyType("youtube")]
		public string Youtube
		{
			get { return this.GetPropertyValue<string>("youtube"); }
		}
	}
}
