//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.10.102
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedContentModels
{
	/// <summary>Om os</summary>
	[PublishedContentModel("omOs")]
	public partial class OmOs : PublishedContentModel, IBannerImg, IBaseConent
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "omOs";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public OmOs(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<OmOs, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Cta bokse
		///</summary>
		[ImplementPropertyType("CtaAbout")]
		public IEnumerable<IPublishedContent> CtaAbout
		{
			get { return this.GetPropertyValue<IEnumerable<IPublishedContent>>("CtaAbout"); }
		}

		///<summary>
		/// Cta overskrift
		///</summary>
		[ImplementPropertyType("ctaAboutHeadline")]
		public string CtaAboutHeadline
		{
			get { return this.GetPropertyValue<string>("ctaAboutHeadline"); }
		}

		///<summary>
		/// Illustration Overskrift
		///</summary>
		[ImplementPropertyType("illustrationHeadline")]
		public string IllustrationHeadline
		{
			get { return this.GetPropertyValue<string>("illustrationHeadline"); }
		}

		///<summary>
		/// Illustration tekst
		///</summary>
		[ImplementPropertyType("illustrationText")]
		public IHtmlString IllustrationText
		{
			get { return this.GetPropertyValue<IHtmlString>("illustrationText"); }
		}

		///<summary>
		/// Banner
		///</summary>
		[ImplementPropertyType("banner")]
		public IPublishedContent Banner
		{
			get { return Umbraco.Web.PublishedContentModels.BannerImg.GetBanner(this); }
		}

		///<summary>
		/// bannerHead
		///</summary>
		[ImplementPropertyType("bannerHead")]
		public string BannerHead
		{
			get { return Umbraco.Web.PublishedContentModels.BannerImg.GetBannerHead(this); }
		}

		///<summary>
		/// Content sub text
		///</summary>
		[ImplementPropertyType("contentSubText")]
		public string ContentSubText
		{
			get { return Umbraco.Web.PublishedContentModels.BaseConent.GetContentSubText(this); }
		}

		///<summary>
		/// Content text
		///</summary>
		[ImplementPropertyType("contentText")]
		public IHtmlString ContentText
		{
			get { return Umbraco.Web.PublishedContentModels.BaseConent.GetContentText(this); }
		}

		///<summary>
		/// Page Title
		///</summary>
		[ImplementPropertyType("pageTitle")]
		public string PageTitle
		{
			get { return Umbraco.Web.PublishedContentModels.BaseConent.GetPageTitle(this); }
		}
	}
}
